apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns-dev
  namespace: external-dns-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns-dev
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions","networking.k8s.io"]
  resources: ["ingresses"] 
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-dev-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns-dev
subjects:
- kind: ServiceAccount
  name: external-dns-dev
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-dev
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns-dev
  template:
    metadata:
      labels:
        app: external-dns-dev
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns-dev
        image: k8s.gcr.io/external-dns/external-dns:v0.13.2
        args:
        - --source=service
        - --source=ingress
        - --domain-filter=mydomain.com
        - --azure-resource-group= MyDnsResourceGroup
        - --provider=azure
        - --registry=txt
        - --txt-prefix=externaldns-
        - --log-level=debug
        volumeMounts:
        - name: azure-config-file
          mountPath: /etc/kubernetes
          readOnly: true
      volumes:
      - name: azure-config-file
        secret:
          secretName: azure-config-file
