#==========================================
# GLOBAL
#==========================================
global:
  env: development
  helmDefault: false
  valuesFile: values.yaml
  spec:
    project: devops
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    source:
      repoURL:
      targetRevision: HEAD



# #==========================================
# # PROJECT
# #==========================================
# project:
#   name:  devops-project
#   description: "DevOps Project"

# #==========================================
# # REPOSITORIES
# #==========================================
# repositories:
#   infra:
#     name: devops
#     url: "git@github.com:Torch-Networks/Ecomm.git"
#     sshPrivateKeySecret: ""

#==========================================
# APPLICATIONS
#==========================================
argocdApplications:
  nginx:
    name: ingress-nginx
    repoURL: "https://kubernetes.github.io/ingress-nginx"
    targetRevision: 4.8.0
    chart: ingress-nginx
    namespace: "ingress-nginx"
    disableAutomated: false
    disable: false
    hasPath: false
    hasChart: true
    helm: true
    hasNameSpace: true
    hasOpcinal: true
    valuesHelm: |
      controller:
        resources:
          limits:
            cpu: 200m
            memory: 180Mi
          requests:
            cpu: 100m
            memory: 90Mi
          # autoscaling:
          #   enabled: enable
          #   minReplicas: 1
          #   maxReplicas: 2
          #   targetCPUUtilizationPercentage: 80
          #   targetMemoryUtilizationPercentage: 80
        metrics:
          enabled: true
        podAnnotations:
          prometheus.io/port: "10254"
          prometheus.io/scrape: "true"
  prometheus:
    name: prometheus
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: 23.1.0
    chart: "prometheus"
    namespace: "prometheus-monitoring"
    disableAutomated: false
    disable: false
    hasPath: false
    hasChart: true
    helm: true
    hasOpcinal: true
    hasNameSpace: true
    valuesHelm: |
      server:
        resources:
           limits:
             cpu: 1
             memory: 1Gi
           requests:
             cpu: 500m
             memory: 512Mi
      extraScrapeConfigs: |
        - job_name: 'argocd'
          metrics_path: /metrics
          static_configs:
            - targets:
              - argocd-application-controller-metrics.argocd.svc.cluster.local:8082
          scrape_interval: 5s
          scheme: "http"
        - job_name: 'external-dns'
          metrics_path: /metrics
          static_configs:
            - targets:
              - external-dns-development.external-dns-system.svc.cluster.local:7979
          scrape_interval: 5s
          scheme: "http"
        - job_name: 'cert-manager'
          metrics_path: /metrics
          static_configs:
            - targets:
              - cert-manager-development.cert-manager.svc.cluster.local:9402
          scrape_interval: 5s
          scheme: "http"
        - job_name: 'nginx'
          metrics_path: /metrics
          static_configs:
            - targets:
              - ingress-nginx-development-metrics.ingress-nginx.svc.cluster.local:10254

          scrape_interval: 5s
          scheme: "http"
        - job_name: 'jaeger'
          metrics_path: /metrics
          static_configs:
            - targets:
              - jaeger-development-collector.jaeger-monitoring.svc.cluster.local:14269
              - jaeger-development-agent.jaeger-monitoring.svc.cluster.local:14271
              - jaeger-development-query.jaeger-monitoring.svc.cluster.local:16687
          scrape_interval: 5s
          scheme: "http"
        - job_name: 'cluster-autoscaler'
          metrics_path: /metrics
          static_configs:
            - targets:
              - autoscaling-development-aws-cluster-autoscaler.autoscaler.svc.cluster.local:8085
          scrape_interval: 5s
          scheme: "http"

  grafana:
    name: grafana
    repoURL: "https://grafana.github.io/helm-charts"
    targetRevision: 6.60.1
    chart: "grafana"
    namespace: "grafana-monitoring"
    disableAutomated: false
    disable: false
    hasPath: false
    hasChart: true
    helm: true
    hasNameSpace: true
    hasOpcinal: true
    valuesHelm: |
      # resources:
      #   limits:
      #     cpu: 1
      #     memory: 1Gi
      #   requests:
      #     cpu: 500m
      #     memory: 512Mi
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus-development-server.prometheus-monitoring.svc.cluster.local
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
      dashboards:
        default:
          argocd:
            gnetId: 14584
            datasource: Prometheus
          external-dns:
            gnetId: 15038
            datasource: Prometheus
          cert-manager:
            gnetId: 11001
            datasource: Prometheus
          nginx:
            gnetId: 9614
            datasource: Prometheus
          jaeger:
            gnetId: 10001
            datasource: Prometheus
          autoscaler:
            gnetId: 3831
            datasource: Prometheus