#==========================================
# GLOBAL
#==========================================
global:
  env: dev
  helmDefault: false
  valuesFile: values.yaml
  spec:
    project: main-project
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    source:
      repoURL:
      targetRevision: HEAD



# #==========================================
# # PROJECT
# #==========================================
# project:
#   name:  devops-project
#   description: "DevOps Project"

# #==========================================
# # REPOSITORIES
# #==========================================
# repositories:
#   infra:
#     name: devops
#     url: "git@github.com:Torch-Networks/Ecomm.git"
#     sshPrivateKeySecret: ""

#==========================================
# APPLICATIONS
#==========================================
argocdApplications:
  nginx:
    name: ingress-nginx
    repoURL: "https://kubernetes.github.io/ingress-nginx"
    targetRevision: 4.8.0
    chart: ingress-nginx
    namespace: "ingress-nginx"
    disableAutomated: false
    disable: false
    hasPath: false
    hasChart: true
    helm: true
    hasNameSpace: true
    hasOpcinal: true
    valuesHelm: |
      controller:
        resources:
          limits:
            cpu: 200m
            memory: 180Mi
          requests:
            cpu: 100m
            memory: 90Mi
          # autoscaling:
          #   enabled: enable
          #   minReplicas: 1
          #   maxReplicas: 2
          #   targetCPUUtilizationPercentage: 80
          #   targetMemoryUtilizationPercentage: 80
        metrics:
          enabled: true
        podAnnotations:
          prometheus.io/port: "10254"
          prometheus.io/scrape: "true"
  prometheus:
    name: prometheus
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: 23.1.0
    chart: "prometheus"
    namespace: "prometheus-monitoring"
    disableAutomated: false
    disable: false
    hasPath: false
    hasChart: true
    helm: true
    hasOpcinal: true
    hasNameSpace: true
    valuesHelm: |
      server:
        resources:
           limits:
             cpu: 1
             memory: 1Gi
           requests:
             cpu: 500m
             memory: 512Mi
      extraScrapeConfigs: |
        - job_name: 'argocd'
          metrics_path: /metrics
          static_configs:
            - targets:
              - argocd-release-application-controller-metrics.argocd.svc.cluster.local:8082
          scrape_interval: 5s
          scheme: "http"

  grafana:
    name: grafana
    repoURL: "https://grafana.github.io/helm-charts"
    targetRevision: 6.60.1
    chart: "grafana"
    namespace: "grafana-monitoring"
    disableAutomated: false
    disable: false
    hasPath: false
    hasChart: true
    helm: true
    hasNameSpace: true
    hasOpcinal: true
    valuesHelm: |
      # resources:
      #   limits:
      #     cpu: 1
      #     memory: 1Gi
      #   requests:
      #     cpu: 500m
      #     memory: 512Mi
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus-dev-server.prometheus-monitoring.svc.cluster.local
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
      dashboards:
        default:
          argocd:
            gnetId: 14584
            datasource: Prometheus
  # external-dns:
  #   name: external-dns
  #   repoURL: "https://kubernetes-sigs.github.io/external-dns"
  #   targetRevision: 1.13.1
  #   chart: "external-dns"
  #   namespace: "external-dns-system"
  #   disableAutomated: false
  #   disable: false
  #   hasPath: false
  #   hasChart: true
  #   helm: true
  #   hasNameSpace: true
  #   hasOpcinal: true
  #   valuesHelm: |
  #     fullNameOverride: external-dns
  #     image:
  #       repository: registry.k8s.io/external-dns/external-dns
  #       tag: v0.13.1
  #     policy: sync
  #     provider: azure
  #     rbac:
  #       create: true
  #     # serviceAccount:
  #     #   create: true
  #     #   annotations:
  #     #     azure.workload.identity/client-id: "/subscriptions/2cda291c-24de-4ef3-9811-45243a5369c1/resourcegroups/MC_resource-test_test--aks_westus3/providers/Microsoft.ManagedIdentity/userAssignedIdentities/test--aks-agentpool/federatedIdentityCredentials/external-dns-credentials"
  #     # podLabels:
  #     #   azure.workload.identity/use: "true"
  #     secretConfiguration:
  #       enabled: true
  #       mountPath: "/etc/kubernetes/"
  #       data:
  #         azure.json: |
  #           {
  #             "tenantId": "d55f6b89-e844-4c2b-b069-ef293ba546ff",
  #             "subscriptionId": "2cda291c-24de-4ef3-9811-45243a5369c1",
  #             "resourceGroup": "resource-test",
  #             "useWorkloadIdentityExtension": true
  #           }